import "./globals.css";

export const metadata = {
  title: "Ankasa App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Poppins:wght@100;200;300;400;500;600;700;800;900&display=swap" />
      </head>
      <body>{children}</body>
    </html>
  );
}
